### ISSUE TITLE
Compile error with Clang 15

### ISSUE THREAD

**Issue by ceeac** [napframework/nap#19] opened 2023-12-01 18:26 UTC
OS: Ubuntu 22.04
To reproduce, build with the following command:
```
mkdir build/ && cd build && cmake -GNinja -DCMAKE_C_COMPILER=clang-15 -DCMAKE_CXX_COMPILER=clang++-15 ..
```
This results in:
```
/home/ceeac/Projects/code/nap/utility/src/utility/stringutils.cpp:119:36: error: use of undeclared identifier 'strncmp'
                        compare_func = caseSensitive ? &strncmp : &strncasecmp;
                                                        ^
/home/ceeac/Projects/code/nap/utility/src/utility/stringutils.cpp:119:47: error: use of undeclared identifier 'strncasecmp'
                        compare_func = caseSensitive ? &strncmp : &strncasecmp;
                                                                   ^
/home/ceeac/Projects/code/nap/utility/src/utility/stringutils.cpp:121:63: error: use of undeclared identifier 'strlen'
                        return compare_func(inString.c_str(), inSubString.c_str(), strlen(inSubString.c_str())) == 0;
                                                                                   ^
/home/ceeac/Projects/code/nap/utility/src/utility/stringutils.cpp:136:36: error: use of undeclared identifier 'strncmp'
                        compare_func = caseSensitive ? &strncmp : &strncasecmp;
                                                        ^
/home/ceeac/Projects/code/nap/utility/src/utility/stringutils.cpp:136:47: error: use of undeclared identifier 'strncasecmp'
                        compare_func = caseSensitive ? &strncmp : &strncasecmp;
                                                                   ^
5 errors generated.
ninja: build stopped: subcommand failed.
```

**Comment by cklosters** [comment] 2023-12-07 12:30
I tried to reproduce your issue on Ubuntu 22.04 and 20.04 without success. I think this has to do with your installed version of `stdc++`, not Clang, GCC or Ubuntu. My steps:

- Fresh install Ubuntu 22.04
- Install Clang-15
- Run check_build_environment to install other dependencies
- Generate solution: `../thirdparty/cmake/linux/x86_64/bin/cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_C_COMPILER=clang-15`
- make `helloworld`

Target compiles (and runs) just fine. I am closing this because we don't support your target compiler and I can't reproduce the issue.

**Closed by cklosters** 2023-12-07 12:30 UTC
Labels: invalid, need more info, build
